name: Measure coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
        cache: gradle
        
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.4

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Coverage
      run: ./gradlew jacocoTestReport     

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v3
      with:
        name: report.xml
        path: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
    
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.3
      if: ${{ github.event_name == 'pull_request' }}
      with:
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the Coverage info
      run: |
        echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
        echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
